# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(587, 193)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.valuesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.valuesGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.valuesGroupBox.setObjectName("valuesGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.valuesGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.valuesFormLayout = QtWidgets.QFormLayout()
        self.valuesFormLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valuesFormLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.valuesFormLayout.setObjectName("valuesFormLayout")
        self.label = QtWidgets.QLabel(self.valuesGroupBox)
        self.label.setObjectName("label")
        self.valuesFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.odDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.valuesGroupBox)
        self.odDoubleSpinBox.setDecimals(1)
        self.odDoubleSpinBox.setMaximum(10.0)
        self.odDoubleSpinBox.setSingleStep(0.5)
        self.odDoubleSpinBox.setProperty("value", 8.0)
        self.odDoubleSpinBox.setObjectName("odDoubleSpinBox")
        self.valuesFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.odDoubleSpinBox)
        self.label_2 = QtWidgets.QLabel(self.valuesGroupBox)
        self.label_2.setObjectName("label_2")
        self.valuesFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.valuesGroupBox)
        self.label_3.setObjectName("label_3")
        self.valuesFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.hsVolumeSpinBox = QtWidgets.QSpinBox(self.valuesGroupBox)
        self.hsVolumeSpinBox.setMaximum(100)
        self.hsVolumeSpinBox.setProperty("value", 20)
        self.hsVolumeSpinBox.setObjectName("hsVolumeSpinBox")
        self.valuesFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hsVolumeSpinBox)
        self.hpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.valuesGroupBox)
        self.hpDoubleSpinBox.setDecimals(1)
        self.hpDoubleSpinBox.setMaximum(10.0)
        self.hpDoubleSpinBox.setSingleStep(0.5)
        self.hpDoubleSpinBox.setProperty("value", 8.0)
        self.hpDoubleSpinBox.setObjectName("hpDoubleSpinBox")
        self.valuesFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hpDoubleSpinBox)
        self.verticalLayout.addLayout(self.valuesFormLayout)
        self.gridLayout_2.addWidget(self.valuesGroupBox, 0, 1, 1, 1)
        self.sampleSetsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.sampleSetsGroupBox.setObjectName("sampleSetsGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sampleSetsGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sampleSetVLayout = QtWidgets.QVBoxLayout()
        self.sampleSetVLayout.setObjectName("sampleSetVLayout")
        self.sampleSetNormalRadioButton = QtWidgets.QRadioButton(self.sampleSetsGroupBox)
        self.sampleSetNormalRadioButton.setChecked(True)
        self.sampleSetNormalRadioButton.setObjectName("sampleSetNormalRadioButton")
        self.sampleSetVLayout.addWidget(self.sampleSetNormalRadioButton)
        self.sampleSetSoftRadioButton = QtWidgets.QRadioButton(self.sampleSetsGroupBox)
        self.sampleSetSoftRadioButton.setObjectName("sampleSetSoftRadioButton")
        self.sampleSetVLayout.addWidget(self.sampleSetSoftRadioButton)
        self.sampleSetDrumRadioButton = QtWidgets.QRadioButton(self.sampleSetsGroupBox)
        self.sampleSetDrumRadioButton.setObjectName("sampleSetDrumRadioButton")
        self.sampleSetVLayout.addWidget(self.sampleSetDrumRadioButton)
        self.verticalLayout_4.addLayout(self.sampleSetVLayout)
        self.gridLayout_2.addWidget(self.sampleSetsGroupBox, 0, 2, 1, 1)
        self.pathsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.pathsGroupBox.setObjectName("pathsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pathsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pathsGridLayout = QtWidgets.QGridLayout()
        self.pathsGridLayout.setObjectName("pathsGridLayout")
        self.outputLineEdit = QtWidgets.QLineEdit(self.pathsGroupBox)
        self.outputLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.pathsGridLayout.addWidget(self.outputLineEdit, 1, 1, 1, 1)
        self.outputToolButton = QtWidgets.QToolButton(self.pathsGroupBox)
        self.outputToolButton.setObjectName("outputToolButton")
        self.pathsGridLayout.addWidget(self.outputToolButton, 1, 2, 1, 1)
        self.inputToolButton = QtWidgets.QToolButton(self.pathsGroupBox)
        self.inputToolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.inputToolButton.setObjectName("inputToolButton")
        self.pathsGridLayout.addWidget(self.inputToolButton, 0, 2, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.pathsGroupBox)
        self.inputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputLabel.setObjectName("inputLabel")
        self.pathsGridLayout.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.outputLabel = QtWidgets.QLabel(self.pathsGroupBox)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.pathsGridLayout.addWidget(self.outputLabel, 1, 0, 1, 1)
        self.inputLineEdit = QtWidgets.QLineEdit(self.pathsGroupBox)
        self.inputLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.pathsGridLayout.addWidget(self.inputLineEdit, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.pathsGridLayout)
        self.gridLayout_2.addWidget(self.pathsGroupBox, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 2)
        self.convertPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertPushButton.setObjectName("convertPushButton")
        self.gridLayout_2.addWidget(self.convertPushButton, 1, 2, 1, 1)
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setObjectName("logLabel")
        self.gridLayout_2.addWidget(self.logLabel, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.odDoubleSpinBox)
        self.label_2.setBuddy(self.hpDoubleSpinBox)
        self.label_3.setBuddy(self.hsVolumeSpinBox)
        self.inputLabel.setBuddy(self.inputLineEdit)
        self.outputLabel.setBuddy(self.outputLineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qua2osu"))
        self.valuesGroupBox.setTitle(_translate("MainWindow", "Values"))
        self.label.setText(_translate("MainWindow", "OD"))
        self.label_2.setText(_translate("MainWindow", "HP"))
        self.label_3.setText(_translate("MainWindow", "Hitsound Volume"))
        self.hsVolumeSpinBox.setSuffix(_translate("MainWindow", "%"))
        self.sampleSetsGroupBox.setTitle(_translate("MainWindow", "Sample Set"))
        self.sampleSetNormalRadioButton.setText(_translate("MainWindow", "Normal"))
        self.sampleSetSoftRadioButton.setText(_translate("MainWindow", "Soft"))
        self.sampleSetDrumRadioButton.setText(_translate("MainWindow", "Drum"))
        self.pathsGroupBox.setTitle(_translate("MainWindow", "Paths"))
        self.outputLineEdit.setPlaceholderText(_translate("MainWindow", "./output"))
        self.outputToolButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open a file dialog to choose where your resulting .osz files should be put</p></body></html>"))
        self.outputToolButton.setText(_translate("MainWindow", "..."))
        self.inputToolButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open a file dialog to select a folder of .qp files</p></body></html>"))
        self.inputToolButton.setText(_translate("MainWindow", "..."))
        self.inputLabel.setText(_translate("MainWindow", "Input Folder"))
        self.outputLabel.setText(_translate("MainWindow", "Output Folder"))
        self.inputLineEdit.setPlaceholderText(_translate("MainWindow", "./input"))
        self.convertPushButton.setText(_translate("MainWindow", "Convert"))
        self.logLabel.setText(_translate("MainWindow", "Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
